dependencies:

- name: "zeitgeist"
  version: 0.5.3
  refPaths:
  - path: hack/verify-dependencies-version.sh
    match: sigs.k8s.io/zeitgeist@v

- name: "golang"
  version: 1.24.0
  refPaths:
  - path: go.mod
    match: "go "
  - path: .golangci.yaml
    match: "go: "
  - path: hack/requirements.sh
    match: "GO_VERSION="

- name: "golangci"
  version: 2.1.5
  refPaths:
  - path: .github/workflows/golangci-lint.yaml
    match: "GOLANGCI_VERSION: "
  - path: hack/update-go-lint.sh
    match: "golangci-lint@v"
  - path: hack/verify-go-lint.sh
    match: "golangci-lint@v"

- name: "kind"
  version: 0.23.0
  refPaths:
  - path: hack/requirements.sh
    match: "KIND_VERSION="
  - path: pkg/consts/consts.go
    match: "KindVersion"

- name: "kubernetes"
  version: 1.32.2
  refPaths:
  - path: supported_releases.txt
    match: ""
  - path: pkg/consts/consts.go
    match: "KubeVersion"
  - path: hack/requirements.sh
    match: "KUBE_VERSION="
