version: "2"
run:
  concurrency: 1
  go: 1.24.0
  allow-parallel-runners: false
  allow-serial-runners: true
linters:
  default: none
  enable:
  - asciicheck
  - bodyclose
  - copyloopvar
  - depguard
  - dogsled
  - errcheck
  - errorlint
  - goconst
  - gocritic
  - gocyclo
  - goprintffuncname
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - prealloc
  - revive
  - staticcheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
          # https://go.dev/doc/go1.16#ioutil
          - pkg: io/ioutil
            desc: please see https://go.dev/doc/go1.16#ioutil
          # Use sigs.k8s.io/kwok/pkg/log, which is a wrapper around slog
          - pkg: k8s.io/klog/v2
            desc: please use `sigs.k8s.io/kwok/pkg/log` instead
          - pkg: k8s.io/klog
            desc: please use `sigs.k8s.io/kwok/pkg/log` instead
          - pkg: golang.org/x/exp/slog
            desc: please use `sigs.k8s.io/kwok/pkg/log` instead
          - pkg: log/slog
            desc: please use `sigs.k8s.io/kwok/pkg/log` instead
          - pkg: log
            desc: please use `sigs.k8s.io/kwok/pkg/log` instead
          # Use sigs.k8s.io/kwok/pkg/utils/yaml, which is a wrapper around yaml
          - pkg: k8s.io/apimachinery/pkg/util/yaml
            desc: please use `sigs.k8s.io/kwok/pkg/utils/yaml` instead
          - pkg: sigs.k8s.io/yaml
            desc: please use `sigs.k8s.io/kwok/pkg/utils/yaml` instead
          # Use sigs.k8s.io/kwok/pkg/utils/wait, which is a wrapper around wait
          - pkg: k8s.io/apimachinery/pkg/util/wait
            desc: please use `sigs.k8s.io/kwok/pkg/utils/wait` instead
          # Use sigs.k8s.io/kwok/pkg/utils/slices, which is a wrapper around slices
          - pkg: k8s.io/utils/strings/slices
            desc: please use `sigs.k8s.io/kwok/pkg/utils/slices` instead
    goconst:
      match-constant: false
      min-len: 5
      min-occurrences: 10
      ignore-tests: true
    gocyclo:
      min-complexity: 50
    importas:
      alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      no-unaliased: true
    revive:
      rules:
      - name: exported
        arguments:
        - disableStutteringCheck
    staticcheck:
      checks:
      - all
      - -ST1000
      - -ST1003
  exclusions:
    generated: lax
    rules:
    # The Kubernetes naming convention for conversion functions uses underscores
    # and intentionally deviates from normal Go conventions to make those function
    # names more readable. Same for SetDefaults_*.
    - linters:
      - revive
      - staticcheck
      text: '(ST1003: should not use underscores in Go names; func (Convert_.*_To_.*|SetDefaults_)|exported: exported function (Convert|SetDefaults)_.* should be of the form)'
    - linters:
      - goconst
      path: (.+)_test\.go
    paths:
    - .*\.zz_generated\..*
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
  - gci
  - gofmt
  - goimports
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(sigs.k8s.io/kwok)
      - blank
      - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
    - .*\.zz_generated\..*
