/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/operator/v1alpha1"
	scheme "sigs.k8s.io/kwok/pkg/client/operator/clientset/versioned/scheme"
)

// KwoksGetter has a method to return a KwokInterface.
// A group's client should implement this interface.
type KwoksGetter interface {
	Kwoks(namespace string) KwokInterface
}

// KwokInterface has methods to work with Kwok resources.
type KwokInterface interface {
	Create(ctx context.Context, kwok *v1alpha1.Kwok, opts v1.CreateOptions) (*v1alpha1.Kwok, error)
	Update(ctx context.Context, kwok *v1alpha1.Kwok, opts v1.UpdateOptions) (*v1alpha1.Kwok, error)
	UpdateStatus(ctx context.Context, kwok *v1alpha1.Kwok, opts v1.UpdateOptions) (*v1alpha1.Kwok, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Kwok, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KwokList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Kwok, err error)
	KwokExpansion
}

// kwoks implements KwokInterface
type kwoks struct {
	client rest.Interface
	ns     string
}

// newKwoks returns a Kwoks
func newKwoks(c *OperatorV1alpha1Client, namespace string) *kwoks {
	return &kwoks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kwok, and returns the corresponding kwok object, and an error if there is any.
func (c *kwoks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Kwok, err error) {
	result = &v1alpha1.Kwok{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kwoks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kwoks that match those selectors.
func (c *kwoks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KwokList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KwokList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kwoks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kwoks.
func (c *kwoks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kwoks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kwok and creates it.  Returns the server's representation of the kwok, and an error, if there is any.
func (c *kwoks) Create(ctx context.Context, kwok *v1alpha1.Kwok, opts v1.CreateOptions) (result *v1alpha1.Kwok, err error) {
	result = &v1alpha1.Kwok{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kwoks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kwok).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kwok and updates it. Returns the server's representation of the kwok, and an error, if there is any.
func (c *kwoks) Update(ctx context.Context, kwok *v1alpha1.Kwok, opts v1.UpdateOptions) (result *v1alpha1.Kwok, err error) {
	result = &v1alpha1.Kwok{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kwoks").
		Name(kwok.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kwok).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kwoks) UpdateStatus(ctx context.Context, kwok *v1alpha1.Kwok, opts v1.UpdateOptions) (result *v1alpha1.Kwok, err error) {
	result = &v1alpha1.Kwok{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kwoks").
		Name(kwok.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kwok).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kwok and deletes it. Returns an error if one occurs.
func (c *kwoks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kwoks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kwoks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kwoks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kwok.
func (c *kwoks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Kwok, err error) {
	result = &v1alpha1.Kwok{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kwoks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
