apiVersion: v2
description: Default stage policy of KWOK (Kubernetes WithOut Kubelet)
type: application
home: https://kwok.sigs.k8s.io
icon: https://github.com/kubernetes-sigs/kwok/raw/main/logo/kwok.png
keywords:
- kubernetes
- kwok
- kwok policy
- simulation
sources:
- https://github.com/kubernetes-sigs/kwok
name: stage-fast
appVersion: v0.6.0-alpha.1
version: 0.0.1
