name: Releases Charts

on:
  push:
    branches:
    - release-*'
    - main
    paths:
    - charts/kwok/Chart.yaml
    - charts/stage-fast/Chart.yaml

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # important parameter for helm chart

    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Upload blob and build index
      run:
        ./hack/releases-helm-charts.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        add-paths: |
          site/static/charts/index.yaml
        token: ${{ env.GH_TOKEN }}
        commit-message: Bump charts
        delete-branch: true
        title: 'Bump charts'
        body: |
          Bump charts

#    - name: Login to ghcr.io
#      run: |
#        helm registry login --username ${GITHUB_ACTOR} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
#    - name: Release Charts to GHCR
#      run: |
#        helm push "${{ env.RELEASE_VERSION }}.tgz" oci://ghcr.io/${{ github.repository }}/charts
